services:
  - type: web
    name: phantom-cava
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.1
      - key: PORT
        value: 3000